[package]
name = "tm-textfile"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
const-cstr = "0.3.0"
machinery = "0.9.0"
machinery-api = "0.2.0"
tm-anode-api = { path = "../tm-anode-api" }
