[package]
name = "tm-anode-api"
version = "0.4.0"
license = "MIT OR Apache-2.0"
description = "API for the tm-anode The Machinery plugin"
repository = "https://github.com/celphase/anode"
edition = "2018"

[dependencies]
const-cstr = "0.3.0"
machinery = "0.10.0"
machinery-api = "0.3.0"
